### PR TITLE
switch to zippy; closes #15

### LINKED ISSUE #15: switch to zippy

### PR DESCRIPTION
**Pull request by enthus1ast**
Signed-off-by: David Krause <enthus1ast@users.noreply.github.com>

### CODE REVIEW

**Review by ringabout — APPROVED** [review]
Nice, thank you!

**Comment by ringabout** [comment]
Hi @enthus1ast it seems that it didn't pass the tests

```
/home/runner/work/xlsx/xlsx/src/xlsx/utils.nim(5, 13) Error: cannot open file: zippy/ziparchives
```

**Comment by enthus1ast** [comment]
mhh strange i ran the tests on my machine sucessfully, i'll check whats the issue

**Comment by enthus1ast** [comment]
@ringabout can you try to remove your zippy installation:

`nimble remove zippy`
and install it again?
`nimble install zippy`

**Comment by enthus1ast** [comment]
@ringabout done, please try again :)

**Comment by ringabout** [comment]
Thanks for your efforts!

**Pull request merged**
